import {
  Infinity as InfinityIcon,
  Timer,
  Wand2,
  Layers,
  Bug,
  Ship,
  Plug,
  Brush,
  Bot,
  MessageCircleQuestion,
  Library,
  Video,
  Wrench,
  Globe,
  type LucideIcon,
} from "lucide-react";
import type { CoverKey } from "./theme";

/** How an offer is transacted — drives the card CTA + checkout behavior. */
export type OfferAction = "subscribe" | "buy" | "book";
export type PriceModel = "subscription" | "one-time" | "fixed" | "from";
export type OfferKind = "pass" | "course" | "digital" | "service" | "engagement";

/** A single chapter inside a micro-course (each ≤5 minutes total). */
export type Lesson = { time: string; title: string };

export type Offering = {
  id: string;
  index: string;
  icon: LucideIcon;
  kind: OfferKind;
  /** Category chip shown on the card, e.g. "Micro-Course", "All-Access". */
  category: string;
  title: string;
  /** One-line hook — the "why" in the shopper's language. */
  tagline: string;
  /** A complete two-line thought (~12–18 words), no truncation. */
  blurb: string;
  price: string;
  priceModel: PriceModel;
  action: OfferAction;
  /** Typographic cover art direction (replaces stock photography). */
  cover: CoverKey;
  /** Total runtime for a course, e.g. "4:12". */
  duration?: string;
  /** Chapter list for a course — powers the curriculum on the detail view. */
  lessons?: Lesson[];
  description: string;
  /** What you learn / what's included — the concierge grounds on these. */
  features: string[];
  stats: { label: string; value: string }[];
  rating: number;
  reviews: number;
  tags: string[];
  cta: string;
  /** Kept for compatibility with image-driven surfaces; empty for courses. */
  images: string[];
  /** Opener questions shown as chips when Ada's chat is empty. */
  chatSeeds?: string[];
};

/**
 * The v0University catalog — the offer ladder of the #1 v0 builder on Earth.
 * Build-once-sell-many content up top, high-ticket services below. One object
 * per card; the swipe feed reads it top to bottom as a value ladder.
 */
export const OFFERINGS: Offering[] = [
  {
    id: "all-access",
    index: "01",
    icon: InfinityIcon,
    kind: "pass",
    category: "All-Access Pass",
    title: "The Pass",
    tagline: "Every course. Every drop. Every update. One key.",
    blurb: "Unlock the full library of micro-courses, the prompt vault, and every new release the moment it ships.",
    price: "$39/mo",
    priceModel: "subscription",
    action: "subscribe",
    cover: "signal",
    description:
      "One key to everything I know about v0. All eight micro-courses, the full prompt library, every template and component drop, and instant access to new releases as I record them. Cancel anytime — but you won't.",
    features: [
      "All 8 micro-courses, start to finish",
      "The complete prompt library",
      "Every future course & drop included",
      "Priority answers from Ada, the AI tutor",
    ],
    stats: [
      { label: "Courses", value: "8+" },
      { label: "Billing", value: "Monthly" },
      { label: "Cancel", value: "Anytime" },
    ],
    rating: 5.0,
    reviews: 412,
    tags: ["All-Access", "Best value", "Subscription"],
    cta: "Get the Pass",
    images: [],
    chatSeeds: ["What's included in the Pass?", "Is it better than buying courses?", "Can I cancel anytime?"],
  },
  {
    id: "ten-minute-app",
    index: "02",
    icon: Timer,
    kind: "course",
    category: "Micro-Course",
    title: "The 10-Minute App",
    tagline: "Prompt to deployed app before your coffee cools.",
    blurb: "The exact sequence I use to take a raw idea to a live, shareable app in a single sitting.",
    price: "$29",
    priceModel: "one-time",
    action: "buy",
    cover: "paper",
    duration: "4:48",
    lessons: [
      { time: "0:00", title: "The one-sentence spec" },
      { time: "1:20", title: "First prompt, first render" },
      { time: "2:55", title: "Two edits to production-ready" },
      { time: "4:10", title: "Ship it and share the link" },
    ],
    description:
      "Speed is a skill. In under five minutes I show you the exact rhythm — spec, prompt, edit, ship — that turns a rough idea into a live app you can send to anyone.",
    features: [
      "The one-sentence spec that sets up the whole build",
      "How to phrase the first prompt so the render lands",
      "The two edits that get you to production-ready",
      "Deploy and share without touching a terminal",
    ],
    stats: [
      { label: "Length", value: "4:48" },
      { label: "Lessons", value: "4" },
      { label: "Level", value: "All" },
    ],
    rating: 4.9,
    reviews: 1876,
    tags: ["Speed", "Fundamentals", "Deploy"],
    cta: "Enroll — $29",
    images: [],
    chatSeeds: ["Is this good for a total beginner?", "What will I build in it?", "Do I need to code?"],
  },
  {
    id: "prompts-that-dont-miss",
    index: "03",
    icon: Wand2,
    kind: "course",
    category: "Micro-Course",
    title: "Prompts That Don't Miss",
    tagline: "Say it once. Get exactly what you pictured.",
    blurb: "The prompt architecture behind 30,000 generations — structure, context, and constraints that land first try.",
    price: "$29",
    priceModel: "one-time",
    action: "buy",
    cover: "sage",
    duration: "4:31",
    lessons: [
      { time: "0:00", title: "Why most prompts drift" },
      { time: "1:10", title: "The four-part prompt frame" },
      { time: "2:40", title: "Giving context without noise" },
      { time: "3:55", title: "Constraints that steer, not cage" },
    ],
    description:
      "After 30,000 generations I stopped guessing. This is the repeatable prompt frame — intent, context, constraints, and reference — that gets the result you pictured on the first pass, not the fifth.",
    features: [
      "The four-part frame every strong prompt uses",
      "How to feed context without confusing the model",
      "Constraints that steer the output precisely",
      "Reference patterns that lock in your taste",
    ],
    stats: [
      { label: "Length", value: "4:31" },
      { label: "Lessons", value: "4" },
      { label: "Level", value: "All" },
    ],
    rating: 5.0,
    reviews: 2314,
    tags: ["Prompting", "Craft", "Most loved"],
    cta: "Enroll — $29",
    images: [],
    chatSeeds: ["Will this work for any project?", "What's the four-part frame?", "How is this different from tips online?"],
  },
  {
    id: "design-systems-one-shot",
    index: "04",
    icon: Layers,
    kind: "course",
    category: "Micro-Course",
    title: "Design Systems in One Shot",
    tagline: "A real system — tokens, type, motion — not a reskin.",
    blurb: "Get v0 to generate a coherent, custom design system with its own voice instead of default components.",
    price: "$29",
    priceModel: "one-time",
    action: "buy",
    cover: "sand",
    duration: "4:56",
    lessons: [
      { time: "0:00", title: "Systems vs. styling" },
      { time: "1:25", title: "Defining tokens the model respects" },
      { time: "3:00", title: "Type and motion as identity" },
      { time: "4:20", title: "Keeping it consistent as you grow" },
    ],
    description:
      "Most sites look the same because they never got a system. Here's how I direct v0 to invent a real one — a named palette, a type voice, a motion grammar — so every screen feels authored, not assembled.",
    features: [
      "The difference between a system and a coat of paint",
      "Design tokens phrased so the model holds them",
      "Type + motion as the core of an identity",
      "Keeping the system coherent across dozens of screens",
    ],
    stats: [
      { label: "Length", value: "4:56" },
      { label: "Lessons", value: "4" },
      { label: "Level", value: "Intermediate" },
    ],
    rating: 4.9,
    reviews: 1102,
    tags: ["Design", "Systems", "Taste"],
    cta: "Enroll — $29",
    images: [],
    chatSeeds: ["Do I need design experience?", "Will my sites stop looking generic?", "What's a design token?"],
  },
  {
    id: "debugging-with-v0",
    index: "05",
    icon: Bug,
    kind: "course",
    category: "Micro-Course",
    title: "Debugging With v0",
    tagline: "Read the error. Break the loop. Move on.",
    blurb: "Turn the scary red screen into a two-minute fix with the exact way I diagnose and unstick any build.",
    price: "$29",
    priceModel: "one-time",
    action: "buy",
    cover: "slate",
    duration: "4:22",
    lessons: [
      { time: "0:00", title: "What the error is actually telling you" },
      { time: "1:15", title: "Escaping the fix-it loop" },
      { time: "2:45", title: "Giving v0 the right clue" },
      { time: "3:50", title: "When to reset vs. repair" },
    ],
    description:
      "Errors aren't failure — they're direction. I'll show you how to read them calmly, feed v0 the one clue that fixes it, and break out of the endless back-and-forth loop that traps most people.",
    features: [
      "How to actually read a v0 error message",
      "The move that escapes the fix-it loop",
      "The single clue that unsticks a broken build",
      "Knowing when to reset instead of repair",
    ],
    stats: [
      { label: "Length", value: "4:22" },
      { label: "Lessons", value: "4" },
      { label: "Level", value: "All" },
    ],
    rating: 4.8,
    reviews: 1445,
    tags: ["Debugging", "Confidence", "Workflow"],
    cta: "Enroll — $29",
    images: [],
    chatSeeds: ["I always get stuck in loops — will this help?", "Is it beginner-friendly?", "What kind of errors?"],
  },
  {
    id: "ship-to-production",
    index: "06",
    icon: Ship,
    kind: "course",
    category: "Micro-Course",
    title: "Ship to Production",
    tagline: "Live, on your domain, with the vars set right.",
    blurb: "The last mile: deploy, connect a custom domain, and handle environment variables without the anxiety.",
    price: "$29",
    priceModel: "one-time",
    action: "buy",
    cover: "clay",
    duration: "4:39",
    lessons: [
      { time: "0:00", title: "Publish in one move" },
      { time: "1:30", title: "Your own domain, connected" },
      { time: "2:50", title: "Environment variables, demystified" },
      { time: "4:00", title: "The pre-launch checklist" },
    ],
    description:
      "A build isn't real until it's live. This is the clean path from preview to production — publishing, wiring a custom domain, and setting environment variables — so launching feels routine, not risky.",
    features: [
      "Publishing your app in a single move",
      "Connecting a custom domain end to end",
      "Environment variables explained simply",
      "A pre-launch checklist you can reuse forever",
    ],
    stats: [
      { label: "Length", value: "4:39" },
      { label: "Lessons", value: "4" },
      { label: "Level", value: "All" },
    ],
    rating: 4.9,
    reviews: 987,
    tags: ["Deploy", "Domains", "Launch"],
    cta: "Enroll — $29",
    images: [],
    chatSeeds: ["Does it cover custom domains?", "What are environment variables?", "Is deploying hard?"],
  },
  {
    id: "integrations-without-fear",
    index: "07",
    icon: Plug,
    kind: "course",
    category: "Micro-Course",
    title: "Integrations Without Fear",
    tagline: "Databases, auth, payments — wired in, calmly.",
    blurb: "Add a database, real login, and checkout to any build using the integration path I trust every time.",
    price: "$29",
    priceModel: "one-time",
    action: "buy",
    cover: "paper",
    duration: "4:52",
    lessons: [
      { time: "0:00", title: "Picking the right integration" },
      { time: "1:35", title: "A database that just works" },
      { time: "3:05", title: "Real authentication" },
      { time: "4:15", title: "Taking a payment" },
    ],
    description:
      "The moment an app needs data, logins, or money, most people freeze. I'll walk you through the exact, calm sequence I use to add a database, real authentication, and payments to any v0 build.",
    features: [
      "Choosing the right integration for the job",
      "Adding a database that just works",
      "Wiring real authentication, not a mock",
      "Taking your first payment safely",
    ],
    stats: [
      { label: "Length", value: "4:52" },
      { label: "Lessons", value: "4" },
      { label: "Level", value: "Intermediate" },
    ],
    rating: 4.9,
    reviews: 1043,
    tags: ["Database", "Auth", "Payments"],
    cta: "Enroll — $29",
    images: [],
    chatSeeds: ["Does it cover auth and payments?", "Which database do you use?", "Is this too advanced for me?"],
  },
  {
    id: "the-redesign-move",
    index: "08",
    icon: Brush,
    kind: "course",
    category: "Micro-Course",
    title: "The Redesign Move",
    tagline: "Restyle any app to S-tier in minutes.",
    blurb: "How I take a plain build and give it a distinctive, premium look without breaking a single feature.",
    price: "$29",
    priceModel: "one-time",
    action: "buy",
    cover: "sage",
    duration: "4:18",
    lessons: [
      { time: "0:00", title: "Diagnose what makes it look cheap" },
      { time: "1:20", title: "Direct the restyle, keep the logic" },
      { time: "2:45", title: "Type, space, and one signal color" },
      { time: "3:45", title: "The final 10% that sells it" },
    ],
    description:
      "Same app, completely different league. This is the redesign move — how I direct v0 to restyle a working build into something that looks expensive, without touching the functionality underneath.",
    features: [
      "Spotting exactly what makes a UI look cheap",
      "Restyling without breaking your logic",
      "Type, spacing, and a single signal color",
      "The final ten percent that makes it look expensive",
    ],
    stats: [
      { label: "Length", value: "4:18" },
      { label: "Lessons", value: "4" },
      { label: "Level", value: "All" },
    ],
    rating: 5.0,
    reviews: 1620,
    tags: ["Design", "Restyle", "Polish"],
    cta: "Enroll — $29",
    images: [],
    chatSeeds: ["Can I redesign an app I already built?", "Will it break my features?", "Do I need taste for this?"],
  },
  {
    id: "agent-grade-builds",
    index: "09",
    icon: Bot,
    kind: "course",
    category: "Micro-Course",
    title: "Agent-Grade Builds",
    tagline: "Add real AI — streaming, tools, the works.",
    blurb: "Put working AI inside your app: streaming chat, tool calls, and structured output using the AI SDK.",
    price: "$29",
    priceModel: "one-time",
    action: "buy",
    cover: "slate",
    duration: "4:59",
    lessons: [
      { time: "0:00", title: "The AI SDK in plain terms" },
      { time: "1:40", title: "Streaming chat that feels alive" },
      { time: "3:10", title: "Giving your AI tools" },
      { time: "4:25", title: "Structured output you can trust" },
    ],
    description:
      "The skill that puts you ahead: shipping real AI features. I'll show you how I use the AI SDK to add streaming chat, tool calling, and structured output — the same engine that powers Ada on this very site.",
    features: [
      "The AI SDK explained without the jargon",
      "Streaming chat that feels genuinely alive",
      "Giving your AI real tools to act with",
      "Structured output you can build logic on",
    ],
    stats: [
      { label: "Length", value: "4:59" },
      { label: "Lessons", value: "4" },
      { label: "Level", value: "Advanced" },
    ],
    rating: 4.9,
    reviews: 894,
    tags: ["AI", "Advanced", "AI SDK"],
    cta: "Enroll — $29",
    images: [],
    chatSeeds: ["Is this the AI on this site?", "How advanced is it?", "What can I build with it?"],
  },
  {
    id: "single-question",
    index: "10",
    icon: MessageCircleQuestion,
    kind: "service",
    category: "Direct Access",
    title: "One Question",
    tagline: "Ask the #1 builder one thing. Get the real answer.",
    blurb: "Stuck on one specific problem? Send it over and get a precise, personal answer from me directly.",
    price: "$97",
    priceModel: "fixed",
    action: "buy",
    cover: "paper",
    description:
      "Sometimes you don't need a course — you need the one answer that unlocks everything. Send me your single hardest v0 question and I'll reply personally with the exact move, in plain language, no fluff.",
    features: [
      "One specific v0 question, answered by me",
      "A precise, actionable reply — not a runaround",
      "Usually answered within one business day",
      "Yours to keep and reference forever",
    ],
    stats: [
      { label: "Format", value: "1 question" },
      { label: "Reply", value: "< 24h" },
      { label: "From", value: "Me" },
    ],
    rating: 5.0,
    reviews: 268,
    tags: ["1:1", "Direct", "Fast"],
    cta: "Ask for $97",
    images: [],
    chatSeeds: ["What kinds of questions work?", "How fast will I hear back?", "Is $97 worth it for one answer?"],
  },
  {
    id: "prompt-library",
    index: "11",
    icon: Library,
    kind: "digital",
    category: "Prompt Library",
    title: "The Prompt Vault",
    tagline: "My tested prompts. Copy, paste, ship.",
    blurb: "A curated, categorized library of the prompts I actually reach for — with notes on when and why each works.",
    price: "$79",
    priceModel: "one-time",
    action: "buy",
    cover: "sand",
    description:
      "The prompts behind the work. A living, categorized vault of the exact prompts I use to start builds, redesign, debug, and add features — each annotated with when to use it and why it lands.",
    features: [
      "100+ battle-tested prompts, categorized",
      "Notes on when and why each one works",
      "Copy-paste ready for any project",
      "Updated as I discover new patterns",
    ],
    stats: [
      { label: "Prompts", value: "100+" },
      { label: "Access", value: "Lifetime" },
      { label: "Updates", value: "Free" },
    ],
    rating: 4.9,
    reviews: 731,
    tags: ["Prompts", "Reference", "Lifetime"],
    cta: "Get the Vault",
    images: [],
    chatSeeds: ["How many prompts are in it?", "Are they organized?", "Do I get future updates?"],
  },
  {
    id: "coaching",
    index: "12",
    icon: Video,
    kind: "service",
    category: "1-on-1 Coaching",
    title: "Live Coaching",
    tagline: "45 minutes, screen to screen, with me.",
    blurb: "Bring your build, your goals, or your roadblock. We solve it together, live, on a private call.",
    price: "$500",
    priceModel: "fixed",
    action: "book",
    cover: "clay",
    description:
      "The fastest way to level up: a private 45-minute session where we work on your actual project together. Bring a roadblock, a business idea, or a build you want to take to the next level — we'll move fast.",
    features: [
      "A private 45-minute video session",
      "We work on your real project, live",
      "Personalized direction for your goals",
      "A recording and action plan to keep",
    ],
    stats: [
      { label: "Length", value: "45 min" },
      { label: "Format", value: "Private" },
      { label: "Recording", value: "Yes" },
    ],
    rating: 5.0,
    reviews: 143,
    tags: ["1:1", "Live", "High-touch"],
    cta: "Book a session",
    images: [],
    chatSeeds: ["What happens on the call?", "Can we work on my project?", "How do I book a time?"],
  },
  {
    id: "custom-chatbot",
    index: "13",
    icon: Bot,
    kind: "engagement",
    category: "Done-For-You",
    title: "Custom AI Chatbot",
    tagline: "A closer like Ada — built for your business.",
    blurb: "I build you an always-on AI concierge that knows your offers and sells for you around the clock.",
    price: "from $2,500",
    priceModel: "from",
    action: "book",
    cover: "sage",
    description:
      "The AI on this page sells while I sleep. I'll build you your own — an always-on concierge trained on your offers, tuned to your voice, and designed to answer questions and close sales 24/7. Fully done-for-you.",
    features: [
      "An AI concierge trained on your business",
      "Tuned to your voice and your offers",
      "Answers and sells around the clock",
      "Built, deployed, and handed off to you",
    ],
    stats: [
      { label: "Delivery", value: "Done-for-you" },
      { label: "Trained on", value: "Your offers" },
      { label: "Runs", value: "24/7" },
    ],
    rating: 5.0,
    reviews: 61,
    tags: ["AI", "Done-for-you", "Sales"],
    cta: "Start a build",
    images: [],
    chatSeeds: ["Could this work for my business?", "What do you need from me?", "How much does it usually run?"],
  },
  {
    id: "done-for-you",
    index: "14",
    icon: Wrench,
    kind: "engagement",
    category: "Custom Projects",
    title: "Built By Me",
    tagline: "Your product, built end-to-end by the best.",
    blurb: "Hand me the vision. I design, build, and ship the whole product on v0 — to a standard you can't fake.",
    price: "from $25k",
    priceModel: "from",
    action: "book",
    cover: "clay",
    description:
      "When it has to be exceptional, I build it myself. Full products, designed and shipped end-to-end on v0 by the #1 builder on the platform. Corporate consulting and custom engagements welcome. Let's talk about what you need.",
    features: [
      "Full product, designed and built by me",
      "Shipped on v0 to a rare standard",
      "Corporate consulting available",
      "A partner who has done this 30,000 times",
    ],
    stats: [
      { label: "Scope", value: "Full product" },
      { label: "Built by", value: "Me" },
      { label: "Standard", value: "S-tier" },
    ],
    rating: 5.0,
    reviews: 29,
    tags: ["High-ticket", "Custom", "Consulting"],
    cta: "Book a call",
    images: [],
    chatSeeds: ["What kinds of projects do you take?", "What's the typical timeline?", "How does pricing work?"],
  },
  {
    id: "license-platform",
    index: "15",
    icon: Globe,
    kind: "engagement",
    category: "License",
    title: "This Platform, Yours",
    tagline: "Sell your own knowledge on a site exactly like this.",
    blurb: "Want this whole concept for your business? I'll adapt this always-on selling platform to whatever you sell.",
    price: "from $5k",
    priceModel: "from",
    action: "book",
    cover: "ink",
    description:
      "This exact concept works for anything — coaches, agencies, creators, products. I'll adapt this platform, its AI closer, and its authority-first design to your business, so you can sell your own expertise while you sleep.",
    features: [
      "This platform adapted to your business",
      "Your own always-on AI closer, like Ada",
      "The authority-first design, your brand",
      "Launch-ready and built to scale",
    ],
    stats: [
      { label: "For", value: "Any business" },
      { label: "Includes", value: "AI closer" },
      { label: "Outcome", value: "Sell 24/7" },
    ],
    rating: 5.0,
    reviews: 18,
    tags: ["License", "White-label", "Scale"],
    cta: "License it",
    images: [],
    chatSeeds: ["Would this work for my industry?", "What's included in a license?", "How is it different from a template?"],
  },
];
